### ISSUE TITLE
TDFA quasi quoters not dealing with \n, etc.

### ISSUE THREAD

**Issue by twanvl** [iconnect/regex#157]
In the block mode `[^\n]` also matches `'\n'`. Here is a minimal example:

    "--\ny" *=~/ [edBlockSensitive|--[^\n]*///|]

This gives `""`, expected output is `y`. Using `ed` does give the expected result.

Conversely, in the non-block mode, `.` does not match `\n`, while the documentation claims that the mode only affects `^` and `$`.

**Comment by cdornan** [comment]
(I am sorry for taking so long to address this issue.)

I make it that the expected output should be `\ny", which is what we see with the PCRE backend. The problem with the TDFA backend is that it doesn't recognise the (in `String representation) `['\','n']` escape sequence &mdash; but you can place a newline character in the regex and it will work fine. Normal use of the TDFA backend will entail building the regex in a Haskell string literal, which will take care of converting ``\n'` escapes into newline characters.

The problem is that neither the quasi quoters nor the TDFA backend are dealing with `\n` escapes.  To fix this I am adding a simple preprocessor to the TDFA quasi-quoter which will translate the Haskell character escapes: `"\a\b\f\n\r\t\v".

Additionally, the preprocessor used to extract the name captures is not handling newlines properly.
